server:
  port: 8080

spring:
  application:
    name: gateway-ms
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students-ms
          uri: lb://STUDENTS-MS
          predicates:
            - Path=/students/**
        - id: grades-ms
          uri: lb://GRADES-MS
          predicates:
            - Path=/grades/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}


#  Ribbon ya no se utiliza con las versiones más recientes de
#  Spring Cloud, ya que se ha movido hacia Spring Cloud LoadBalancer.